# Generated by Django 3.0.8 on 2020-09-20 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='date_recieve',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transection_date',
            field=models.DateField(),
        ),
    ]
