# Generated by Django 3.0.8 on 2020-09-20 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rest', '0003_auto_20200920_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='date_recieve',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transection_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
